@startuml
start

:Завантаження даних з CSV;
:Перетворення дат у DataFrame;
:Перевірка наявності даних;
if (Чи є відсутні або некоректні дані?) then (так)
  :Обробка відсутніх або некоректних даних;
else (ні)
endif

:Перевірка на викиди;
if (Чи є викиди у даних?) then (так)
  :Коригування викидів;
else (ні)
endif

:Обчислення об'єму продажів;
:Обчислення середнього чеку;
:Аналіз географічного розподілу продажів;
:Аналіз частоти повторних покупок;
:Обчислення середнього часу від реєстрації до покупки;
:Обчислення проценту успішних транзакцій;
:Обчислення проценту повернень;
:Обчислення середнього часу онлайн до покупки;
:Аналіз ефективності маркетингових каналів;
:Аналіз рівня лояльності клієнтів;

:Візуалізація результатів;

stop
@enduml